SELECT
  DW_DIM_CANCEL_GR.CANCELGROUP AS CANCELLATION_CATEGORY,
  initcap(lower(DW_DIM_CANCEL_REASON.CANCELLATIONDESC)) AS CANCELLATION_REASON,
  ((count(DW_CANC.POLICYID))) AS COUNT,
  to_char(DW_CANC.REPORTPERIOD,'YYYY') AS YEAR
FROM
  DWADMIN.DW_CANC,
  DWADMIN.DW_DIM_CANCEL_REASON,
  DWADMIN.DW_DIM_CANCEL_GR
WHERE
  ( DW_CANC.CANCELLATIONREASONID=DW_DIM_CANCEL_REASON.CANCELLATIONID  )
  AND  ( DW_DIM_CANCEL_REASON.CANCELLATIONGROUP=DW_DIM_CANCEL_GR.CANCELGROUP_ID  )
  AND  
  to_char(DW_CANC.REPORTPERIOD,'YYYY')  =  '2015'
GROUP BY
  DW_DIM_CANCEL_GR.CANCELGROUP, 
  initcap(lower(DW_DIM_CANCEL_REASON.CANCELLATIONDESC)), 
  to_char(DW_CANC.REPORTPERIOD,'YYYY')


